[[redirects]]
  from = "/:slug.html"
  to = "/:slug"
  status = 301
  force = true

[[redirects]]
  from = "/:slug"
  to = "/:slug.html"
  status = 200

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
