
[[redirects]]
  from = "/*"
  to = "/:splat.html"
  status = 200


[[redirects]]
  from = "/*.html"
  to = "/:splat"
  status = 301

[[redirects]]
  from = "/:path/*.html"
  to = "/:path/*"
  status = 301
